#!/bin/bash
#set -x

KAFKA_LOG_FILE="kafka_runtime.log"
KAFKA_CONFIG_FILE="/opt/kafka-latest/config/server.properties"
KAFKA_EXE="/opt/kafka-latest/bin/kafka-server-start.sh"

if [ ! -d "${KAFKA_DATA_DIR}" ]; then
    mkdir -p "${KAFKA_DATA_DIR}"
fi

if [ ! -d "${KAFKA_LOG_DIR}" ]; then
    mkdir -p "${KAFKA_LOG_DIR}"
fi                                            

if [ -x "${KAFKA_EXE}" ]; then
    command="${KAFKA_EXE} ${KAFKA_CONFIG_FILE} >> ${KAFKA_LOG_DIR}/${KAFKA_LOG_FILE} 2>&1"
fi

if [ "${command}" != "" ]; then
    eval exec "${command}"
fi
