#!/bin/bash
#set -x
PATH="/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"
TERM="vt100"
export TERM PATH

PATH="/opt/kafka-latest/bin:${PATH}"
KAFKA_CONFIG_FILE="/opt/kafka-latest/config/server.properties"
KAFKA_EXE=$(which kafka-server-start.sh 2> /dev/null)

if [ ! -d "${KAFKA_DATA_DIR}" ]; then
    mkdir -p "${KAFKA_DATA_DIR}"
fi

if [ ! -d "${KAFKA_LOG_DIR}" ]; then
    mkdir -p "${KAFKA_LOG_DIR}"
fi                                            

if [ -x "${KAFKA_EXE}" ]; then
    sed -i -e "s|::KAFKA_DATA_DIR::|${KAFKA_DATA_DIR}|g" "${KAFKA_CONFIG_FILE}"
    command="${KAFKA_EXE} ${KAFKA_CONFIG_FILE} >> ${KAFKA_LOG_DIR}/${KAFKA_LOG_FILE} 2>&1"
fi

if [ "${command}" != "" ]; then
    eval exec "${command}"
fi
