#!/bin/bash
#set -x
PATH="/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"
TERM="vt100"
export TERM PATH

KAFKA_REST_PROPERTIES="/etc/kafka-rest/kafka-rest.properties"
KAFKA_REST_EXE=$(which kafka-rest-start 2> /dev/null)

if [ ! -d "${KAFKA_REST_LOG_DIR}" ]; then
    mkdir -p "${KAFKA_REST_LOG_DIR}"
fi

if [ -x "${KAFKA_REST_EXE}" ]; then
    command="${KAFKA_REST_EXE} ${KAFKA_REST_PROPERTIES} >> ${KAFKA_REST_LOG_DIR}/${KAFKA_REST_LOG_FILE} 2>&1"
fi

if [ "${command}" != "" ]; then
    eval exec "${command}"
fi
